apiVersion: v1
kind: Service
metadata:
  name: movie-bot-service
spec:
  type: NodePort
  selector:
    app: movie-bot
  ports:
    - port: 80
      targetPort: 8110
      nodePort: 30080
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: movie-bot
spec:
  replicas: 1
  selector:
    matchLabels:
      app: movie-bot
  template:
    metadata:
      labels:
        app: movie-bot
    spec:
      containers:
        - name: bot
          image: movie-bot:latest
          imagePullPolicy: Never # Берем образ из локального Docker/Kind
          ports:
            - containerPort: 8110
          # Подключаем переменные из Secret и ConfigMap
          envFrom:
            - secretRef:
                name: bot-secrets
            - configMapRef:
                name: bot-config