version: '3.8'

services:
  db:
    image: postgres:15-alpine
    container_name: movie_recommendation_db
    restart: unless-stopped
    environment:
      POSTGRES_DB: ${DB_NAME:-users_db}
      POSTGRES_USER: ${DB_USERNAME:-users_db}
      DB_PASSWORD: ${POSTGRES_DB_PASSWORD}
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./init-db/users_db.sql:/docker-entrypoint-initdb.d/init.sql:ro
    networks:
      - app-network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${DB_USERNAME:-users_db} -d ${DB_NAME:-users_db}"]
      interval: 10s
      timeout: 5s
      retries: 5

  app:
    image: polyalugovenko/movie-recommendation-bot:latest
    container_name: movie-bot-poly
    restart: unless-stopped
    environment:
      DB_URL: ${DB_URL}
      DB_USERNAME: ${DB_USERNAME}
      DB_PASSWORD: ${POSTGRES_DB_PASSWORD}
      BOT_TOKEN: ${BOT_TOKEN}
      BOT_USERNAME: ${BOT_USERNAME}
      # App config
      ADMIN_PASSWORD: ${ADMIN_PASSWORD:?error}
      API_KEY: ${API_KEY:?error}
      HTTP_PORT: ${HTTP_PORT:-8110}
      HTTP_HOST: ${HTTP_HOST:-0.0.0.0}
    depends_on:
      db:
        condition: service_healthy
    ports:
      - "${HTTP_PORT:-8110}:8110"
    networks:
      - app-network
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"

volumes:
  postgres_data:

networks:
  app-network: